[private]
dev-private ansible_host=10.0.2.179 ansible_user=ubuntu

[nat]
dev-nat ansible_host=3.109.133.190 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@13.232.134.200"'