- name: Configure NAT
  hosts: nat
  become: yes
  roles:
    - nat

- name: Setup Docker
  hosts: private
  become: yes
  roles:
    - docker

- name: Deploy App
  hosts: private
  become: yes
  roles:
    - app

- name: Setup CloudWatch
  hosts: private
  become: yes
  roles:
    - cloudwatch